# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: alsaeed <alsaeed@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/11 14:48:47 by alsaeed           #+#    #+#              #
#    Updated: 2023/09/26 16:19:05 by alsaeed          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

$(NAME): all

all: 
	@make all -C src
	
clean:
	@make clean -C src

fclean: clean
	@make fclean -C src

re: fclean all